spring:
  rabbitmq:
    host: 192.168.65.229
    username: ly
    password: 1024
    # 必须指明，否则不生效
    # none 关闭发布确认模式
    # correlated 异步确认
    # simple 同步确认
    publisher-confirm-type: correlated

    # 开启不可路由的消息，退回给生产者
    publisher-returns: true